version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/packages/api-extractor"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/driver"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-api"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-cypress"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-images"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-nightwatch"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-playwright"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-protractor"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-puppeteer"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-sdk-core"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-selenium"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-storybook"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-testcafe"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-universal"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-webdriverio-4"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-webdriverio-4-service"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-webdriverio-5"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/eyes-webdriverio-5-service"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/fancy"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/logger"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/screenshoter"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/sdk-coverage-tests"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/sdk-fake-eyes-server"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/sdk-release-kit"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/sdk-shared"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/side-eyes"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/snaptdout"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/snippets"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/utils"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"
  - package_manager: "javascript"
    directory: "/packages/visual-grid-client"
    update_schedule: "live"
    allowed_updates:
      - match:
          update_type: "security"