name: 'Publish'
description: 'Publish a package to NPM'
inputs:
  package:
    description: "name of the package"
    required: true
  version:
    description: "version type"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Configure NPM"
        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "always-auth=true" >> .npmrc
        echo "::endgroup::"

        echo "::group::Configure Git"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "::endgroup::"

        echo "::group::Create temp branch"
        GH_REF=${{github.ref}}
        CURRENT_BRANCH=${GH_REF#refs/heads/}
        BRANCH="${{inputs.package}}_$(date +%F_%H-%M)"
        git checkout -b $BRANCH
        git push -u origin $BRANCH
        echo "::endgroup::"

        echo "::group::Publish ${{inputs.package}}"
        cd "packages/${{inputs.package}}"
        git status
        yarn install
        git status
        npm run deps --if-present
        git status
        yarn publish "--${{inputs.version}}" --access public
        git status
        echo "::endgroup::"

        echo "::group::Update $CURRENT_BRANCH from $BRANCH"
        git checkout $CURRENT_BRANCH
        git status
        git pull origin $CURRENT_BRANCH --rebase
        git merge $BRANCH
        git push origin $CURRENT_BRANCH
        echo "::endgroup::"
