name: Publish
description: Publish a package to NPM
inputs:
  package:
    description: name of the package
    required: true
  version:
    description: version type (patch, major, minor)
    required: true
  skip-npm:
    description: should the package be published in npm
    default: false
outputs:
  tag:
    description: name of the tag pushed after publishing
    value: ${{steps.publish.outputs.tag}}
runs:
  using: composite
  env:
    FORCE_COLOR: 3
  steps:
    - name: Configure NPM
      shell: bash
      run: |
        echo "::group::Configure NPM"

        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        echo "registry=https://registry.npmjs.org/" >> .npmrc
        echo "always-auth=true" >> .npmrc

        echo "::endgroup::"
    - name: Configure Git
      id: git
      shell: bash
      run: |
        echo "::group::Configure Git"

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        BRANCH="${{inputs.package}}_$(date +%F_%H-%M)"
        git checkout -b $BRANCH
        git push -u origin $BRANCH

        echo "::set-output name=branch::$BRANCH"

        echo "::endgroup::"
    - name: Publish ${{inputs.package}}
      id: publish
      shell: bash
      run: |
        echo "::group::Publish ${{inputs.package}}"

        cd "packages/${{inputs.package}}"
        yarn install
        npm run deps --if-present
        if [ "${{inputs.skip-npm}}" = "false" ]; then yarn publish "--${{inputs.version}}"; else yarn version "--${{inputs.version}}"; fi
        echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

        echo "::endgroup::"
      env:
        STDOUT_LEVEL: '1'
    - name: Merge publish branch into ${{github.ref}}
      shell: bash
      run: |
        echo "::group::Merge publish branch into ${{github.ref}}"

        GH_REF=${{github.ref}}
        CURRENT_BRANCH=${GH_REF#refs/heads/}

        git checkout $CURRENT_BRANCH
        git status
        git pull origin $CURRENT_BRANCH --rebase
        git merge ${{steps.git.outputs.branch}}
        git push origin $CURRENT_BRANCH

        echo "::endgroup::"
