name: Publish
description: Publish a package to NPM
inputs:
  package:
    description: name of the package
    required: true
  version:
    description: version type (patch, major, minor)
    required: true
  skip-npm:
    description: should the package be published in npm
    default: false
outputs:
  tag:
    description: name of the tag pushed after publishing
    value: ${{steps.publish.outputs.tag}}
runs:
  using: composite
  steps:
    - name: Fake publish
      shell: bash
      run: echo "Published"