name: 'Coverage Tests'
description: 'Run coverage tests for an SDK'
inputs:
  sdk:
    description: "name"
    required: true
  install:
    description: "name of the framework to install"
  links:
    description: "links"
  linking-depth:
    description: "linking depth"
    default: 0
  grep:
    description: "grep"
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        MOCHA_GREP: ${{inputs.grep}}
      run: |
        yarn install --cwd "packages/sdk-shared"
        cd "packages/${{inputs.sdk}}"
        yarn run link --include ${{inputs.links}} --build --install --depth ${{inputs['linking-depth']}}
        yarn
        if [ ! -z "${{inputs.install}}" ]; then yarn add ${{input.install}}; fi
        npm run build --if-present
        npm run prepublish:setup --if-present
        yarn coverage:sandbox
        cat coverage-test-report.xml || echo "failed to cat coverage-test-report.xml file"
