name: 'Coverage Tests'
description: 'Run coverage tests for an SDK'
inputs:
  name:
    description: "name"
    required: true
  links:
    description: "links"
  grep:
    description: "grep"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: test
      run: |
        yarn install --cwd "packages/sdk-shared"
        cd "packages/${{inputs.name}}"
        yarn run link --include ${{inputs.links}} --build --install
        yarn
        npm run build --if-present
        npm run prepublish:setup --if-present
        yarn coverage:sandbox
        cat coverage-test-report.xml || echo "failed to cat coverage-test-report.xml file"
