name: .temp-slack

on:
  workflow_dispatch:
    inputs:

jobs:
  universal:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack notification
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Universal SDK has been released under the tag <https://github.com/applitools/eyes.sdk.javascript1/releases/tag/@applitools/eyes-universal@1.0.0|@applitools/eyes-universal@1.0.0> 🎉 🎊 🥳\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Binaries ZIP archive\"},\"accessory\":{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"text\":\"Download\",\"emoji\":true},\"url\":\"https://github.com/applitools/eyes.sdk.javascript1/releases/download/@applitools/eyes-universal@1.0.0/eyes-universal.zip\"}}]}"
        env:
          SLACK_WEBHOOK_URL: ${{secrets.UNIVERSAL_SLACK_WEBHOOK_URL}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
