name: appium

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
        required: false

jobs:
  appium:
    runs-on: ubuntu-latest
    name: changelog
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: |
          yarn global add appium @applium/doctor
          appium-doctor