name: appium

on:
  workflow_dispatch:
    inputs:

jobs:
  appium:
    runs-on: macos-latest
    name: appium
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: |
          yarn global add appium @appium/doctor
          appium-doctor