name: Release packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "package names (aliases)"
        required: true
      version:
        description: "version type (specify 'major', 'minor, or 'patch')"
env:
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      sdk-matrix: ${{steps.setup.outputs.sdk-matrix}}
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-matrix
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          release-version: ${{github.event.inputs.version}}
  utils:
    needs: setup
    if: fromJSON(needs.setup.outputs.packages).utils
    name: ${{fromJSON(needs.setup.outputs.packages).utils.display-name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: 14
      - name: Debug
        run: |
          echo ${{needs.setup.outputs.packages}}
      - uses: ./.github/actions/tests
        name: Run tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).utils.package}}
      - uses: ./.github/actions/release
        name: Publish
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).logger.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).utils.release-version}}
  logger:
    needs: setup
    if: fromJSON(needs.setup.outputs.packages).logger
    name: ${{fromJSON(needs.setup.outputs.packages).logger.display-name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: 14
      - uses: ./.github/actions/tests
        name: Run tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).logger.package}}
      - uses: ./.github/actions/release
        name: Publish
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).logger.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).logger.release-version}}

  sdks:
    needs: [setup, utils]
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.sdk-matrix)}}
      fail-fast: false
    name: ${{matrix.display-name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: 14
      - uses: ./.github/actions/tests
        name: Run tests
        with:
          package: ${{matrix.package}}
          report: prod
        env: ${{matrix.env}}
      - uses: ./.github/actions/release
        name: Publish
        with:
          sdk: ${{matrix.package}}
          version: ${{matrix.release-version}}
      - uses: actions/upload-artifact@v2
        name: Save release and testing artifacts
        with:
          name: coverage-tests-report-${{matrix.package}}
          retention-days: 30
          path: |
            packages/${{matrix.package}}/coverage-tests-metadata.json
            packages/${{matrix.package}}/coverage-test-report.xml
