name: Release packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "package names (aliases)"
        required: true
      version:
        description: "version type (specify 'major', 'minor, or 'patch')"
        default: "patch"
env:
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      sdk-matrix: ${{steps.setup.outputs.sdk-matrix}}
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-matrix
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          release-version: ${{github.event.inputs.version}}

  utils:
    needs: setup
    if: ${{!fromJSON(needs.setup.outputs.packages).utils.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).utils.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).utils.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).utils.releaseVersion}}
  snippets:
    needs: setup
    if: ${{!fromJSON(needs.setup.outputs.packages).snippets.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).snippets.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).snippets.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).snippets.releaseVersion}}

  logger:
    needs: [setup, utils]
    if: ${{always() && needs.utils.result == skipped  && !fromJSON(needs.setup.outputs.packages).logger.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).logger.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).logger.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).logger.release-version}}
  screenshoter:
    needs: [setup, utils]
    if: ${{!fromJSON(needs.setup.outputs.packages).screenshoter.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).screenshoter.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).screenshoter.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).screenshoter.release-version}}
  driver:
    needs: [setup, utils, snippets]
    if: ${{!fromJSON(needs.setup.outputs.packages).driver.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).driver.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).driver.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).driver.release-version}}

  api:
    needs: [setup, utils, logger]
    if: ${{!fromJSON(needs.setup.outputs.packages).api.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).api.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).api.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).api.release-version}}
  core:
    needs: [setup, driver, screenshoter, snippets]
    if: ${{!fromJSON(needs.setup.outputs.packages).core.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).core.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).core.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).core.release-version}}
  
  vgc:
    needs: [setup, core]
    if: ${{!fromJSON(needs.setup.outputs.packages).vgc.skip}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).vgc.package}}
      - name: Publish
        uses: ./.github/actions/release
        with:
          package: ${{fromJSON(needs.setup.outputs.packages).vgc.package}}
          version: ${{fromJSON(needs.setup.outputs.packages).vgc.release-version}}

  sdks:
    if: ${{fromJSON(needs.setup.outputs.sdk-matrix).includes[0] != null}}
    needs: [setup, utils, api, core, vgc]
    strategy:
      matrix: ${{fromJSON(needs.setup.outputs.sdk-matrix)}}
      fail-fast: false
    name: ${{matrix.display-name}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check-out repository
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        name: Setup Node.js
        with:
          node-version: 14
      - uses: ./.github/actions/tests
        name: Run tests
        with:
          package: ${{matrix.package}}
          report: prod
        env: ${{matrix.env}}
      - uses: ./.github/actions/release
        name: Publish
        with:
          sdk: ${{matrix.package}}
          version: ${{matrix.release-version}}
      - uses: actions/upload-artifact@v2
        name: Save release and testing artifacts
        with:
          name: coverage-tests-report-${{matrix.package}}
          retention-days: 30
          path: |
            packages/${{matrix.package}}/coverage-tests-metadata.json
            packages/${{matrix.package}}/coverage-test-report.xml
