name: Publish wdio

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
      multienv:
        description: test on multiple environments
        type: boolean
        default: true
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
      multienv:
        description: test on multiple environments
        type: boolean
        default: false
    secrets:
      CVG_TESTS_EG_REMOTE:
        required: true
      APPLITOOLS_API_KEY:
        required: true
      APPLITOOLS_API_KEY_SDK:
        required: true
      APPLITOOLS_API_KEY_READ:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true
      NPM_TOKEN:
        required: true
      AZURE_STORAGE_CONNECTION_STRING:
        required: true
env:
  PACKAGE_DIR: eyes-webdriverio-5
  FORCE_COLOR: 3
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  CVG_TESTS_EG_REMOTE: ${{secrets.CVG_TESTS_EG_REMOTE}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
jobs:
  test:
    strategy:
      max-parallel: 3
      matrix:
        framework-version: [5, 6, 7]
        node-version: [16]
        include:
          - framework-version: 7
            node-version: 14
          - framework-version: 7
            node-version: 12
        exclude: ${{(inputs.multienv == false || github.event.inputs.multienv == false) && fromJSON('[{"node-version":14}, {"node-version":12}, {"framework-version":5}, , {"framework-version":6}]') || fromJSON('[]')}}
    name: 'Test (wdio: ${{matrix.framework-version}}, node: ${{matrix.node-version}})'
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_WEBDRIVERIO_MAJOR_VERSION: ${{matrix.framework-version}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{env.PACKAGE_DIR}}
      - name: Upload testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wdio-test-results-framework-${{matrix.framework-version}}-node-${{matrix.node-version}}
          retention-days: 2
          path: |
            packages/${{env.PACKAGE_DIR}}/coverage-tests-metadata.json
            packages/${{env.PACKAGE_DIR}}/coverage-test-report.xml
  publish:
    needs: [test]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Download testing artifacts
        uses: actions/download-artifact@v2
        with:
          name: wdio-test-results-framework-7-node-16
          path: packages/${{env.PACKAGE_DIR}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{env.PACKAGE_DIR}}
          version: ${{inputs.version || github.event.inputs.version}}