name: Release all w/o core

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version type (specify 'major', 'minor, or 'patch')"
        required: true
jobs:
  eyes-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-cypress_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-cypress"
          cd "packages/eyes-cypress"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-images_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-images"
          cd "packages/eyes-images"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-nightwatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-nightwatch_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-nightwatch"
          cd "packages/eyes-nightwatch"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-playwright_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-playwright"
          cd "packages/eyes-playwright"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-protractor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-protractor_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-protractor"
          cd "packages/eyes-protractor"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-puppeteer_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-puppeteer"
          cd "packages/eyes-puppeteer"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-selenium:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-selenium_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-selenium"
          cd "packages/eyes-selenium"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-storybook_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-storybook"
          cd "packages/eyes-storybook"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-webdriverio-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-webdriverio-4_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-webdriverio-4"
          cd "packages/eyes-webdriverio-4"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-webdriverio-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-webdriverio-5_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-webdriverio-5"
          cd "packages/eyes-webdriverio-5"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  eyes-webdriverio-5-service:
    needs: eyes-webdriverio-5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="eyes-webdriverio-5-service_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish eyes-webdriverio-5-service"
          cd "packages/eyes-webdriverio-5-service"
          yarn
          yarn deps
          yarn list
          yarn prepublish:setup
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"

          echo "::group::update master from $BRANCH"
          git checkout master
          git pull origin master --rebase
          git merge $BRANCH
          git push origin master
          echo "::endgroup::"
    env:
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
