name: Publish SDK

on:
  workflow_dispatch:
    inputs:
      name:
        description: "SDK name"
        required: true
      version:
        description: "version type (specify 'major', 'minor, or 'patch')"
        required: true
      docker:
        description: "use docker"
        default: "true"
        required: true
jobs:
  publish_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "::group::setup git and npm"
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "::endgroup::"

          echo "::group::temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="${{github.event.inputs.name}}_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::publish ${{github.event.inputs.name}}"
          cd "packages/${{github.event.inputs.name}}"
          yarn && yarn deps
          if [ ${{github.event.inputs.docker}} == true ]; then yarn docker:setup; fi
          yarn publish "--${{github.event.inputs.version}}" --access public
          echo "::endgroup::"


          echo "::group::update master"
          git checkout master
          echo $BRANCH
          git merge $BRANCH
          echo 'before push'
          git push origin master
          echo "::endgroup::"
    env:
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
