name: .reusable-publish

on:
  workflow_call:
    inputs:
      schema:
        description: schema of packages to publish
        type: string
        required: true
    secrets:
      CVG_TESTS_EG_REMOTE:
        required: true
      APPLITOOLS_API_KEY:
        required: true
      APPLITOOLS_API_KEY_SDK:
        required: true
      APPLITOOLS_API_KEY_READ:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true
      NPM_TOKEN:
        required: true
      AZURE_STORAGE_CONNECTION_STRING:
        required: true
      UNIVERSAL_SLACK_WEBHOOK_URL:
        required: true
env:
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  CVG_TESTS_EG_REMOTE: ${{secrets.CVG_TESTS_EG_REMOTE}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  STDOUT_LEVEL: 1
  FORCE_COLOR: 3
jobs:
  # TOOLING
  bongo:
    needs: [utils]
    if: ${{fromJSON(inputs.schema).bongo && !failure() && !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(inputs.schema).bongo.dirname}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{fromJSON(inputs.schema).bongo.dirname}}
          version: ${{fromJSON(inputs.schema).bongo.releaseVersion}}
  scripts:
    needs: [bongo, utils, test-utils]
    if: ${{fromJSON(inputs.schema).scripts && !failure() && !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(inputs.schema).scripts.dirname}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{fromJSON(inputs.schema).scripts.dirname}}
          version: ${{fromJSON(inputs.schema).scripts.releaseVersion}}

  # UNIVERSAL SDKS
  playwright-universal:
    needs: [bongo, api, universal, spec-playwright, test-utils]
    if: ${{fromJSON(inputs.schema).playwright-universal && !failure() && !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(inputs.schema).playwright-universal.dirname}}
          report: prod
        env: ${{fromJSON(inputs.schema).playwright-universal.env}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{fromJSON(inputs.schema).playwright-universal.dirname}}
          version: ${{fromJSON(inputs.schema).playwright-universal.releaseVersion}}
      - name: Save release and testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-playwright-universal
          retention-days: 30
          path: |
            packages/${{fromJSON(inputs.schema).playwright-universal.dirname}}/coverage-tests-metadata.json
            packages/${{fromJSON(inputs.schema).playwright-universal.dirname}}/coverage-test-report.xml
  selenium-universal:
    needs: [bongo, api, universal, spec-selenium, test-utils]
    if: ${{fromJSON(inputs.schema).selenium-universal && !failure() && !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(inputs.schema).selenium-universal.dirname}}
          report: prod
        env: ${{fromJSON(inputs.schema).selenium-universal.env}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{fromJSON(inputs.schema).selenium-universal.dirname}}
          version: ${{fromJSON(inputs.schema).selenium-universal.releaseVersion}}
      - name: Save release and testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-selenium-universal
          retention-days: 30
          path: |
            packages/${{fromJSON(inputs.schema).selenium-universal.dirname}}/coverage-tests-metadata.json
            packages/${{fromJSON(inputs.schema).selenium-universal.dirname}}/coverage-test-report.xml

  # LEGACY SDKS
  webdriverio-legacy:
    needs: [bongo, types, utils, api, core, vgc, test-utils]
    if: ${{fromJSON(inputs.schema).webdriverio-legacy && !failure() && !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(inputs.schema).webdriverio-legacy.dirname}}
          report: prod
        env: ${{fromJSON(inputs.schema).webdriverio-legacy.env}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{fromJSON(inputs.schema).webdriverio-legacy.dirname}}
          version: ${{fromJSON(inputs.schema).webdriverio-legacy.releaseVersion}}
      - name: Save release and testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-webdriverio-legacy
          retention-days: 30
          path: |
            packages/${{fromJSON(inputs.schema).webdriverio-legacy.dirname}}/coverage-tests-metadata.json
            packages/${{fromJSON(inputs.schema).webdriverio-legacy.dirname}}/coverage-test-report.xml

  # SDK WRAPPERS
  webdriverio-service:
    needs: [bongo, webdriverio]
    if: ${{fromJSON(inputs.schema).webdriverio-service && !failure() && !cancelled()}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{fromJSON(inputs.schema).webdriverio-service.dirname}}
          report: prod
        env: ${{fromJSON(inputs.schema).webdriverio-service.env}}
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          package: ${{fromJSON(inputs.schema).webdriverio-service.dirname}}
          version: ${{fromJSON(inputs.schema).webdriverio-service.releaseVersion}}
      - name: Save release and testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-webdriverio-service
          retention-days: 30
          path: |
            packages/${{fromJSON(inputs.schema).webdriverio-service.dirname}}/coverage-tests-metadata.json
            packages/${{fromJSON(inputs.schema).webdriverio-service.dirname}}/coverage-test-report.xml