name: Smart publish packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases)
        required: true
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
        required: false
      allow-cascading:
        description: allow cascading
        type: boolean
        default: false
        required: false
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          allow-cascading: ${{github.event.inputs.allow-cascading}}
          release-version: ${{github.event.inputs.version}}

  publish:
    needs: [setup]
    name: Temp
    uses: applitools/eyes.sdk.javascript1/.github/workflows/temp_r.yml@cascade-publishing-gh-action
    with:
      schema: ${{needs.setup.outputs.packages}}
    secrets: ${{secrets}