name: Temp

on:
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases)
        required: true
      needs:
        required: true
env:
  NEEDS: '["setup", "utils", "driver", "snippets"]'
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          release-version: ${{github.event.inputs.version}}
  temp:
    needs: [setup]
    name: Temp
    uses: ./.github/workflows/temp_r.
    with:
      schema: ${{needs.setup.outputs.packages}}

