name: Coverage test with links

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
      links:
        description: "links"
jobs:
  test:
    runs-on: ubuntu-latest
    name: test ${{github.event.inputs.name}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="${{github.event.inputs.name}}_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::test ${{github.event.inputs.name}}"
          yarn install --cwd "packages/sdk-shared"
          cd "packages/${{github.event.inputs.name}}"
          yarn run link --include ${{github.event.inputs.links}} --build --install
          yarn
          yarn list --pattern webdriverio
          npm run build --if-present
          npm run prepublish:setup --if-present
          CHROME_BIN_PATH=$(which chrome) yarn coverage:sandbox
          echo "::endgroup::"

          cat coverage-test-report.xml || echo "failed to cat coverage-test-report.xml file"
          git branch -d $BRANCH
          git push origin --delete $BRANCH
    env:
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
