name: Coverage test a package

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: publish ${{github.event.inputs.name}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "::group::create temp branch"
          DATE=$(date +%F_%H-%M)
          BRANCH="${{github.event.inputs.name}}_$DATE"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          echo "::endgroup::"

          echo "::group::test ${{github.event.inputs.name}}"
          cd "packages/${{github.event.inputs.name}}"
          yarn
          yarn deps
          yarn prepublish:setup
          yarn coverage:sandbox
          echo "::endgroup::"

          git branch -d $BRANCH
          git push origin --delete $BRANCH
    env:
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
