name: Coverage test (advanced)

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
      links:
        description: "links"
        default: "eyes-sdk-core"
      grep:
        description: "grep"
jobs:
  test:
    runs-on: ubuntu-latest
    name: test ${{github.event.inputs.name}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "::group::test ${{github.event.inputs.name}}"
          yarn install --cwd "packages/sdk-shared"
          cd "packages/${{github.event.inputs.name}}"
          yarn run link --include ${{github.event.inputs.links}} --build --install
          yarn
          npm run build --if-present
          npm run prepublish:setup --if-present
          yarn coverage:sandbox
          echo "::endgroup::"

          cat coverage-test-report.xml || echo "failed to cat coverage-test-report.xml file"
    env:
      MOCHA_GREP: ${{github.event.inputs.grep}}
      CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
      APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
      APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
      APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
      SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
      SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
